---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue
spec:
  replicas: 2
  selector:
    matchLabels:
      platform: vue
  template:
    metadata:
      labels:
        platform: vue
    spec:
      containers:
          image: vue
          name: vue
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
      imagePullSecrets:
        - name: my-container-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    platform: vue
  name: vue
spec:
  ports:
    - port: 5173
      name: vue
  selector:
    platform: vue
  type: NodePort


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vue
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: vue.sys
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vue
                port:
                  name: vue