apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: vue
build:
  artifacts:
    - image: vue
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s-skaffold.yaml

portForward:
  - resourceType: deployment
    resourceName: vue
    port: 5173
    localPort: 9999